apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-demo-app
  namespace: default
  labels:
    app: envoy-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: envoy-demo
  template:
    metadata:
      labels:
        app: envoy-demo
    spec:
      containers:
        - name: podinfo
          image: ghcr.io/stefanprodan/podinfo:latest
          resources:
            requests:
              cpu: "10m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
          ports:
            - containerPort: 9898
---
apiVersion: v1
kind: Service
metadata:
  name: envoy-demo-svc
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 9898
  selector:
    app: envoy-demo
